CREATE TABLE "affiliate_conversions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"linkId" bigint NOT NULL,
	"programId" bigint NOT NULL,
	"orderId" varchar(100),
	"orderValue" numeric(10, 2) NOT NULL,
	"commissionAmount" numeric(10, 2) NOT NULL,
	"status" text DEFAULT 'pending',
	"customerIp" varchar(100),
	"userAgent" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "affiliate_links" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"programId" bigint NOT NULL,
	"influencerId" bigint NOT NULL,
	"uniqueCode" varchar(20) NOT NULL,
	"uniqueUrl" text,
	"clicks" integer DEFAULT 0,
	"uniqueClicks" integer DEFAULT 0,
	"conversions" integer DEFAULT 0,
	"commissionEarned" numeric(12, 2) DEFAULT '0',
	"status" text DEFAULT 'active',
	"joinedAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "affiliate_links_uniqueCode_unique" UNIQUE("uniqueCode")
);
--> statement-breakpoint
CREATE TABLE "affiliate_programs" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"brandId" bigint NOT NULL,
	"programName" varchar(255) NOT NULL,
	"description" text,
	"commissionType" text DEFAULT 'percentage',
	"commissionRate" numeric(5, 2) NOT NULL,
	"commissionAmount" numeric(10, 2) DEFAULT '0',
	"productName" varchar(255),
	"productValue" numeric(10, 2),
	"productUrl" text,
	"cookieDuration" integer DEFAULT 30,
	"minFollowers" integer DEFAULT 0,
	"creatorCategories" json,
	"status" text DEFAULT 'active',
	"totalCreatorsJoined" integer DEFAULT 0,
	"totalClicks" integer DEFAULT 0,
	"totalConversions" integer DEFAULT 0,
	"totalCommissionPaid" numeric(12, 2) DEFAULT '0',
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_matches" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"requirementId" bigint NOT NULL,
	"influencerId" bigint NOT NULL,
	"matchScore" integer NOT NULL,
	"matchReason" text,
	"categoryMatch" integer DEFAULT 0,
	"followerMatch" integer DEFAULT 0,
	"engagementMatch" integer DEFAULT 0,
	"locationMatch" integer DEFAULT 0,
	"budgetMatch" integer DEFAULT 0,
	"platformMatch" integer DEFAULT 0,
	"status" text DEFAULT 'suggested',
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "barter_applications" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"dealId" bigint NOT NULL,
	"influencerId" bigint NOT NULL,
	"message" text,
	"proposedDeliverables" text,
	"contentLinks" json,
	"contentSubmittedAt" timestamp,
	"status" text DEFAULT 'applied',
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "barter_deals" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"brandId" bigint NOT NULL,
	"productName" varchar(255) NOT NULL,
	"productDescription" text,
	"productValue" numeric(10, 2),
	"productImage" text,
	"contentType" json,
	"deliverables" text,
	"creatorCategories" json,
	"minFollowers" integer,
	"maxFollowers" integer,
	"minEngagementRate" numeric(5, 2),
	"preferredPlatforms" json,
	"preferredLocation" varchar(100),
	"campaignStart" date,
	"campaignEnd" date,
	"instructions" text,
	"status" text DEFAULT 'open',
	"slotsTotal" integer DEFAULT 1,
	"slotsFilled" integer DEFAULT 0,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "brand_profiles" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"userId" bigint NOT NULL,
	"companyName" varchar(255) NOT NULL,
	"brandName" varchar(255),
	"industry" varchar(100),
	"website" varchar(255),
	"description" text,
	"email" varchar(320),
	"phone" varchar(20),
	"location" varchar(100),
	"city" varchar(100),
	"teamSize" varchar(50),
	"budgetRange" varchar(50),
	"logo" text,
	"verified" boolean DEFAULT false,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "brand_requirements" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"brandId" bigint NOT NULL,
	"campaignTitle" varchar(255) NOT NULL,
	"campaignDescription" text,
	"contentTypes" json,
	"creatorCategories" json,
	"minFollowers" integer,
	"maxFollowers" integer,
	"minEngagementRate" numeric(5, 2),
	"preferredPlatforms" json,
	"budgetPerCreator" numeric(12, 2),
	"totalBudget" numeric(12, 2),
	"creatorsNeeded" integer DEFAULT 1,
	"minReachExpected" integer,
	"minLikesExpected" integer,
	"preferredLocation" varchar(100),
	"campaignStart" date,
	"campaignEnd" date,
	"status" text DEFAULT 'draft',
	"autoMatched" boolean DEFAULT false,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "brand_subscriptions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"brandId" bigint NOT NULL,
	"plan" text DEFAULT 'free' NOT NULL,
	"monthlyPrice" numeric(10, 2) DEFAULT '0',
	"commissionRate" numeric(5, 2) DEFAULT '15',
	"maxActiveCampaigns" integer DEFAULT 1,
	"canUseAiMatching" boolean DEFAULT false,
	"canUseRoiTracking" boolean DEFAULT false,
	"canUseAffiliate" boolean DEFAULT false,
	"canFeatureCampaigns" boolean DEFAULT false,
	"status" text DEFAULT 'trial',
	"trialEndsAt" timestamp,
	"currentPeriodStart" timestamp DEFAULT now(),
	"currentPeriodEnd" timestamp,
	"totalDealsClosed" integer DEFAULT 0,
	"totalCommissionPaid" numeric(12, 2) DEFAULT '0',
	"totalSubscriptionPaid" numeric(12, 2) DEFAULT '0',
	"paymentMethodId" varchar(255),
	"lastPaymentDate" timestamp,
	"lastPaymentStatus" text DEFAULT 'none',
	"failedPaymentCount" integer DEFAULT 0,
	"gracePeriodEndsAt" timestamp,
	"reminderSentAt" timestamp,
	"downgradeScheduledAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "brand_subscriptions_brandId_unique" UNIQUE("brandId")
);
--> statement-breakpoint
CREATE TABLE "campaign_analytics" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"campaignId" bigint NOT NULL,
	"brandId" bigint NOT NULL,
	"totalSpend" numeric(12, 2) DEFAULT '0',
	"totalRevenue" numeric(12, 2) DEFAULT '0',
	"totalClicks" integer DEFAULT 0,
	"totalConversions" integer DEFAULT 0,
	"totalImpressions" integer DEFAULT 0,
	"roi" numeric(8, 2) DEFAULT '0',
	"cpc" numeric(10, 2) DEFAULT '0',
	"cpa" numeric(10, 2) DEFAULT '0',
	"conversionRate" numeric(5, 2) DEFAULT '0',
	"startDate" timestamp DEFAULT now(),
	"endDate" timestamp,
	"reportGenerated" boolean DEFAULT false,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "campaign_analytics_campaignId_unique" UNIQUE("campaignId")
);
--> statement-breakpoint
CREATE TABLE "campaign_applications" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"campaignId" bigint NOT NULL,
	"influencerId" bigint NOT NULL,
	"message" text,
	"proposedRate" numeric(10, 2),
	"status" text DEFAULT 'pending',
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_tracking" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"campaignId" bigint NOT NULL,
	"applicationId" bigint NOT NULL,
	"trackingUrl" varchar(500) NOT NULL,
	"shortCode" varchar(20) NOT NULL,
	"clicks" integer DEFAULT 0,
	"uniqueClicks" integer DEFAULT 0,
	"impressions" integer DEFAULT 0,
	"conversions" integer DEFAULT 0,
	"revenueGenerated" numeric(12, 2) DEFAULT '0',
	"status" text DEFAULT 'active',
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "campaign_tracking_shortCode_unique" UNIQUE("shortCode")
);
--> statement-breakpoint
CREATE TABLE "campaigns" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"brandId" bigint NOT NULL,
	"requirementId" bigint,
	"title" varchar(255) NOT NULL,
	"description" text,
	"requirements" text,
	"platform" text DEFAULT 'all',
	"contentType" text DEFAULT 'all',
	"budget" numeric(12, 2),
	"creatorCount" integer DEFAULT 1,
	"niche" varchar(100),
	"location" varchar(100),
	"followerMin" integer,
	"followerMax" integer,
	"status" text DEFAULT 'draft',
	"startDate" date,
	"endDate" date,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "creator_subscriptions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"creatorId" bigint NOT NULL,
	"plan" text DEFAULT 'free' NOT NULL,
	"monthlyPrice" numeric(10, 2) DEFAULT '0',
	"hasVerifiedBadge" boolean DEFAULT false,
	"hasMediaKit" boolean DEFAULT false,
	"canGetFeatured" boolean DEFAULT false,
	"canGetPriorityMatching" boolean DEFAULT false,
	"canGetTaxInvoices" boolean DEFAULT false,
	"earlyAccessCampaigns" boolean DEFAULT false,
	"status" text DEFAULT 'trial',
	"trialEndsAt" timestamp,
	"currentPeriodStart" timestamp DEFAULT now(),
	"currentPeriodEnd" timestamp,
	"totalEarnings" numeric(12, 2) DEFAULT '0',
	"totalSubscriptionPaid" numeric(12, 2) DEFAULT '0',
	"paymentMethodId" varchar(255),
	"lastPaymentDate" timestamp,
	"lastPaymentStatus" text DEFAULT 'none',
	"failedPaymentCount" integer DEFAULT 0,
	"gracePeriodEndsAt" timestamp,
	"reminderSentAt" timestamp,
	"downgradeScheduledAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "creator_subscriptions_creatorId_unique" UNIQUE("creatorId")
);
--> statement-breakpoint
CREATE TABLE "credit_scores" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"creatorId" bigint NOT NULL,
	"overallScore" integer DEFAULT 0,
	"scoreCategory" text DEFAULT 'poor',
	"contentConsistencyScore" integer DEFAULT 0,
	"brandReliabilityScore" integer DEFAULT 0,
	"audienceQualityScore" integer DEFAULT 0,
	"engagementAuthenticityScore" integer DEFAULT 0,
	"financialReliabilityScore" integer DEFAULT 0,
	"complianceScore" integer DEFAULT 0,
	"growthVelocityScore" integer DEFAULT 0,
	"platformDiversityScore" integer DEFAULT 0,
	"positiveFactors" json,
	"negativeFactors" json,
	"improvementTips" json,
	"previousScore" integer DEFAULT 0,
	"scoreChange" integer DEFAULT 0,
	"reportGenerated" boolean DEFAULT false,
	"reportUrl" text,
	"calculatedAt" timestamp DEFAULT now() NOT NULL,
	"nextCalculationAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "credit_scores_creatorId_unique" UNIQUE("creatorId")
);
--> statement-breakpoint
CREATE TABLE "featured_campaigns" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"campaignId" bigint NOT NULL,
	"barterDealId" bigint,
	"featureType" text NOT NULL,
	"durationDays" integer DEFAULT 7,
	"pricePaid" numeric(10, 2) NOT NULL,
	"status" text DEFAULT 'active',
	"featuredAt" timestamp DEFAULT now() NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"impressionsGenerated" integer DEFAULT 0,
	"clicksGenerated" integer DEFAULT 0,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "influencer_profiles" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"userId" bigint NOT NULL,
	"fullName" varchar(255) NOT NULL,
	"displayName" varchar(255) NOT NULL,
	"bio" text,
	"email" varchar(320),
	"phone" varchar(20),
	"instagramId" varchar(100),
	"facebookId" varchar(100),
	"youtubeId" varchar(100),
	"tiktokId" varchar(100),
	"twitterId" varchar(100),
	"linkedinId" varchar(100),
	"categories" json,
	"niche" varchar(100),
	"location" varchar(100),
	"city" varchar(100),
	"followerCount" integer DEFAULT 0,
	"engagementRate" numeric(5, 2),
	"avgLikes" integer DEFAULT 0,
	"avgComments" integer DEFAULT 0,
	"avgReach" integer DEFAULT 0,
	"platforms" json,
	"ratePerPost" numeric(10, 2),
	"ratePerStory" numeric(10, 2),
	"ratePerReel" numeric(10, 2),
	"ratePerVideo" numeric(10, 2),
	"portfolioLinks" json,
	"sampleWork" text,
	"avatar" text,
	"verified" boolean DEFAULT false,
	"availableForCollaboration" boolean DEFAULT true,
	"matchScore" integer DEFAULT 0,
	"igTotalFollowers" integer DEFAULT 0,
	"igTotalFollowing" integer DEFAULT 0,
	"igPostsCount" integer DEFAULT 0,
	"igAvgLikes" integer DEFAULT 0,
	"igAvgComments" integer DEFAULT 0,
	"igEngagementRate" numeric(5, 2),
	"igLikeEngagementRate" numeric(5, 2),
	"igCommentEngagementRate" numeric(5, 2),
	"igPostFrequency" numeric(4, 1),
	"igTopHashtags" json,
	"igContentTypes" json,
	"igFakeFollowerScore" integer DEFAULT 0,
	"igFakeFollowerPercentage" integer DEFAULT 0,
	"igFollowerQualityRating" varchar(20),
	"igEstimatedReach" integer DEFAULT 0,
	"igEstimatedImpressions" integer DEFAULT 0,
	"igAudienceActivity" varchar(20),
	"igOverallScore" integer DEFAULT 0,
	"igOverallRating" varchar(20),
	"igAnalyticsFetchedAt" timestamp,
	"igIsVerified" boolean DEFAULT false,
	"igIsPrivate" boolean DEFAULT false,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "interested_users" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(320) NOT NULL,
	"phone" varchar(20),
	"userType" text NOT NULL,
	"instagramHandle" varchar(100),
	"niche" varchar(100),
	"followerRange" varchar(50),
	"companyName" varchar(255),
	"website" varchar(255),
	"industry" varchar(100),
	"message" text,
	"status" text DEFAULT 'new' NOT NULL,
	"adminNotes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "language_preferences" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"creatorId" bigint NOT NULL,
	"primaryLanguage" varchar(50) DEFAULT 'hindi',
	"secondaryLanguages" json,
	"contentLanguage" varchar(50) DEFAULT 'hindi',
	"state" varchar(100),
	"city" varchar(100),
	"tier" text DEFAULT 'tier2',
	"vernacularNiches" json,
	"upcomingFestivals" json,
	"isVernacularCreator" boolean DEFAULT false,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "language_preferences_creatorId_unique" UNIQUE("creatorId")
);
--> statement-breakpoint
CREATE TABLE "media_kits" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"userId" bigint NOT NULL,
	"headline" varchar(255),
	"about" text,
	"achievements" json,
	"totalCollaborations" integer DEFAULT 0,
	"totalBrandsWorkedWith" integer DEFAULT 0,
	"featuredWorks" json,
	"testimonials" json,
	"isPublic" boolean DEFAULT true,
	"vanityUrl" varchar(100),
	"viewCount" integer DEFAULT 0,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "media_kits_userId_unique" UNIQUE("userId"),
	CONSTRAINT "media_kits_vanityUrl_unique" UNIQUE("vanityUrl")
);
--> statement-breakpoint
CREATE TABLE "negotiation_sessions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"campaignId" bigint NOT NULL,
	"brandId" bigint NOT NULL,
	"influencerId" bigint NOT NULL,
	"brandBudgetMin" numeric(10, 2) NOT NULL,
	"brandBudgetMax" numeric(10, 2) NOT NULL,
	"brandDeliverables" json,
	"brandUrgency" text DEFAULT 'medium',
	"creatorAskingRate" numeric(10, 2) NOT NULL,
	"creatorMinimumRate" numeric(10, 2),
	"creatorAvailability" text DEFAULT '1week',
	"aiSuggestedRate" numeric(10, 2),
	"aiReasoning" text,
	"marketBenchmarkRate" numeric(10, 2),
	"status" text DEFAULT 'pending',
	"agreedRate" numeric(10, 2),
	"agreedDeliverables" json,
	"messages" json,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"expiresAt" timestamp
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"userId" bigint NOT NULL,
	"title" varchar(255) NOT NULL,
	"message" text,
	"type" text DEFAULT 'info',
	"read" boolean DEFAULT false,
	"isRead" boolean DEFAULT false,
	"actionUrl" varchar(500),
	"metadata" json,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"campaignId" bigint,
	"brandId" bigint NOT NULL,
	"influencerId" bigint NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"subtotal" numeric(12, 2) NOT NULL,
	"gstAmount" numeric(10, 2) DEFAULT '0',
	"gstRate" numeric(5, 2) DEFAULT '18',
	"currency" varchar(10) DEFAULT 'INR',
	"gateway" varchar(50) DEFAULT 'razorpay',
	"gatewayPaymentId" varchar(255),
	"gatewayStatus" text DEFAULT 'pending',
	"status" text DEFAULT 'pending',
	"description" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform_analytics" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"snapshotDate" date NOT NULL,
	"snapshotMonth" varchar(7) NOT NULL,
	"totalUsers" integer DEFAULT 0,
	"newUsers" integer DEFAULT 0,
	"newBrands" integer DEFAULT 0,
	"newInfluencers" integer DEFAULT 0,
	"activeUsers" integer DEFAULT 0,
	"totalRevenue" numeric(14, 2) DEFAULT '0',
	"subscriptionRevenue" numeric(14, 2) DEFAULT '0',
	"commissionRevenue" numeric(14, 2) DEFAULT '0',
	"featuredRevenue" numeric(14, 2) DEFAULT '0',
	"gstCollected" numeric(14, 2) DEFAULT '0',
	"totalPayments" integer DEFAULT 0,
	"totalInEscrow" integer DEFAULT 0,
	"totalReleased" integer DEFAULT 0,
	"totalRefunded" integer DEFAULT 0,
	"totalCampaigns" integer DEFAULT 0,
	"activeCampaigns" integer DEFAULT 0,
	"completedCampaigns" integer DEFAULT 0,
	"totalApplications" integer DEFAULT 0,
	"activeBrandSubs" integer DEFAULT 0,
	"activeCreatorSubs" integer DEFAULT 0,
	"failedPayments" integer DEFAULT 0,
	"churnedUsers" integer DEFAULT 0,
	"userGrowthRate" numeric(6, 2) DEFAULT '0',
	"revenueGrowthRate" numeric(6, 2) DEFAULT '0',
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform_config" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"key" varchar(100) NOT NULL,
	"value" text NOT NULL,
	"description" varchar(255),
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "platform_config_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "platform_fees" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"payerUserId" bigint NOT NULL,
	"payerType" text NOT NULL,
	"campaignId" bigint,
	"paymentId" bigint,
	"feeType" text NOT NULL,
	"baseAmount" numeric(12, 2) NOT NULL,
	"feeRate" numeric(5, 2) DEFAULT '0',
	"feeAmount" numeric(12, 2) NOT NULL,
	"netAmount" numeric(12, 2) NOT NULL,
	"description" varchar(255),
	"ipAddress" varchar(100),
	"processedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "promotions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"code" varchar(50) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"promotionType" text NOT NULL,
	"discountValue" numeric(5, 2) DEFAULT '0',
	"maxUses" integer DEFAULT 0,
	"currentUses" integer DEFAULT 0,
	"maxDealsPerUser" integer DEFAULT 0,
	"minSpend" numeric(10, 2) DEFAULT '0',
	"eligibleUserType" text DEFAULT 'all',
	"status" text DEFAULT 'active',
	"startsAt" timestamp DEFAULT now() NOT NULL,
	"endsAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "promotions_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "regional_trends" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"trendName" varchar(255) NOT NULL,
	"trendDescription" text,
	"category" varchar(100),
	"language" varchar(50) NOT NULL,
	"region" varchar(100),
	"searchVolumeGrowth" numeric(8, 2) DEFAULT '0',
	"engagementGrowth" numeric(8, 2) DEFAULT '0',
	"creatorCount" integer DEFAULT 0,
	"predictedPeakDate" timestamp,
	"confidence" numeric(5, 2) DEFAULT '0',
	"status" text DEFAULT 'emerging',
	"contentSuggestions" json,
	"suggestedHashtags" json,
	"source" varchar(100),
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_consents" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"userId" bigint NOT NULL,
	"termsAccepted" boolean DEFAULT false,
	"privacyAccepted" boolean DEFAULT false,
	"cookiesAccepted" boolean DEFAULT false,
	"marketingAccepted" boolean DEFAULT false,
	"ipAddress" varchar(100),
	"userAgent" text,
	"acceptedAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_consents_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "user_promotion_usage" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"userId" bigint NOT NULL,
	"promotionId" bigint NOT NULL,
	"usageCount" integer DEFAULT 1,
	"lastUsedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"unionId" varchar(255) NOT NULL,
	"name" varchar(255),
	"email" varchar(320),
	"avatar" text,
	"passwordHash" text,
	"role" text DEFAULT 'user' NOT NULL,
	"onboardingComplete" boolean DEFAULT false,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignInAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_unionId_unique" UNIQUE("unionId")
);
